baseURL = "https://interlock.github.io/promise-interactor/"
# relativeURLs = true
canonifyURLs = true
languageCode = "en-us"
title = "Promise Interactor"
description = "Promise based interactor pattern"
theme = "kube"
publishDir = "../docs"

# [[menu.main]]
#    name = "Docs"
#    weight = -100
#    url = "/docs/"
